osx_image: xcode9.2
language: objective-c
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
podfile: Example/Podfile
script:
  - set -o pipe fail && xcodebuild -workspace Example/Example.xcworkspace -scheme Example | xcpretty
